PERMISSIONS = [
    ("dashboard.view", "View dashboard", "Dashboard"),
    ("subscriber.view", "View subscribers", "Subscribers"),
    ("subscriber.create", "Create subscribers", "Subscribers"),
    ("subscriber.edit", "Edit subscribers", "Subscribers"),
    ("subscriber.disable", "Disable subscribers", "Subscribers"),
    ("package.view", "View packages", "Packages"),
    ("package.manage", "Manage packages", "Packages"),
    ("voucher.view", "View vouchers", "Vouchers"),
    ("voucher.generate", "Generate vouchers", "Vouchers"),
    ("voucher.export", "Export vouchers", "Vouchers"),
    ("voucher.disable", "Disable vouchers", "Vouchers"),
    ("session.view", "View sessions", "Sessions"),
    ("session.disconnect", "Disconnect sessions", "Sessions"),
    ("router.view", "View routers", "Networking"),
    ("router.manage", "Manage routers", "Networking"),
    ("analytics.view", "View analytics", "Analytics"),
    ("role.manage", "Manage roles", "Access Control"),
    ("user.manage", "Manage tenant users", "Access Control"),
    ("audit.view", "View audit logs", "Audit"),
    ("settings.manage", "Manage tenant settings", "Settings"),
]
