import os
import re
import secrets
import tempfile
import time
from pathlib import Path

from django.conf import settings
from django.db import transaction
from django.utils import timezone

from .mikrotik import MikroTikClient, MikroTikError
from .models import Router
from .wireguard import allocate_tunnel_ip, build_provisioning, generate_keypair


def _default_api_port(protocol: str) -> int:
    return {Router.APIProtocol.API: 8728, Router.APIProtocol.API_SSL: 8729, Router.APIProtocol.REST: 443}[protocol]


@transaction.atomic
def provision_router(*, tenant, data: dict):
    pair = generate_keypair()
    protocol = data.get("api_protocol", Router.APIProtocol.API)
    router = Router(
        tenant=tenant,
        name=data["name"],
        description=data.get("description", ""),
        tunnel_ip=allocate_tunnel_ip(),
        wireguard_public_key=pair.public_key,
        api_protocol=protocol,
        api_port=data.get("api_port") or _default_api_port(protocol),
        api_username=data["api_username"],
        api_tls_verify=data.get("api_tls_verify", False),
    )
    router.set_api_password(data["api_password"])
    router.set_radius_secret(secrets.token_urlsafe(32))
    router.save()
    transaction.on_commit(render_radius_clients)
    return router, build_provisioning(router, pair.private_key)


def rotate_radius_secret(router: Router) -> str:
    secret = secrets.token_urlsafe(32)
    router.set_radius_secret(secret)
    router.save(update_fields=["radius_secret_cipher", "updated_at"])
    render_radius_clients()
    return secret


def rotate_wireguard(router: Router) -> dict:
    old_public_key = router.wireguard_public_key
    pair = generate_keypair()
    router.wireguard_public_key = pair.public_key
    router.status = Router.Status.PENDING
    router.save(update_fields=["wireguard_public_key", "status", "updated_at"])
    return build_provisioning(router, pair.private_key, old_public_key=old_public_key)


def render_radius_clients() -> str:
    destination = Path(settings.RADIUS_CLIENTS_FILE)
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by PamirNet. Do not edit manually.", ""]
    for router in Router.objects.filter(enabled=True).select_related("tenant").order_by("tunnel_ip"):
        shortname = f"pamirnet-{str(router.id).replace('-', '')[:12]}"
        lines.extend(
            [
                f"client {shortname} {{",
                f"    ipaddr = {router.tunnel_ip}",
                f"    secret = {router.get_radius_secret()}",
                "    nas_type = other",
                f"    shortname = {shortname}",
                f"    # tenant={router.tenant_id} router={router.id}",
                "}",
                "",
            ]
        )
    content = "\n".join(lines)
    fd, temporary = tempfile.mkstemp(prefix="pamirnet-radius-", dir=str(destination.parent))
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.chmod(temporary, 0o600)
        os.replace(temporary, destination)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return content


def parse_uptime_seconds(value) -> int | None:
    if value in (None, ""):
        return None
    if isinstance(value, (int, float)):
        return int(value)
    text = str(value).strip().lower()
    total = 0
    for number, unit in re.findall(r"(\d+)([wdhms])", text):
        total += int(number) * {"w": 604800, "d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
    # RouterOS may return forms such as 1w2d03:04:05.
    if ":" in text:
        tail = text.split("d")[-1].split("w")[-1]
        if re.fullmatch(r"\d{1,2}:\d{2}:\d{2}", tail):
            hours, minutes, seconds = map(int, tail.split(":"))
            total += hours * 3600 + minutes * 60 + seconds
    return total or None


def check_router_health(router: Router, attempts: int = 3) -> dict:
    if not router.enabled:
        router.status = Router.Status.DISABLED
        router.save(update_fields=["status", "updated_at"])
        return {"status": router.status, "packet_loss_percent": 100.0}

    latencies = []
    resource = None
    last_error = ""
    for _ in range(max(1, attempts)):
        started = time.monotonic()
        try:
            resource = MikroTikClient(router).resource()
            latencies.append((time.monotonic() - started) * 1000)
        except MikroTikError as exc:
            last_error = str(exc)

    successes = len(latencies)
    packet_loss = round((1 - successes / max(1, attempts)) * 100, 2)
    router.packet_loss_percent = packet_loss
    router.latency_ms = round(sum(latencies) / successes, 2) if successes else None
    if successes:
        router.status = Router.Status.ONLINE
        router.last_seen_at = timezone.now()
        router.routeros_version = str((resource or {}).get("version", ""))[:80]
        router.uptime_seconds = parse_uptime_seconds((resource or {}).get("uptime"))
    else:
        router.status = Router.Status.OFFLINE
    router.save(
        update_fields=[
            "status",
            "last_seen_at",
            "routeros_version",
            "uptime_seconds",
            "latency_ms",
            "packet_loss_percent",
            "updated_at",
        ]
    )
    return {
        "status": router.status,
        "latency_ms": router.latency_ms,
        "packet_loss_percent": router.packet_loss_percent,
        "last_seen_at": router.last_seen_at,
        "routeros_version": router.routeros_version,
        "uptime_seconds": router.uptime_seconds,
        "error": last_error if not successes else "",
    }
